# Generated by Django 2.2.5 on 2019-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='badWordCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='goodWordCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='isGood',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='isGood',
            field=models.BooleanField(default=True),
        ),
    ]
